title: Richard (Ricky) Tegtmeier  # You can add your name here

logo: image.jpeg # Use a relative path to logo image 

description: PhD Candidate  
Plant Breeding & Genetics  
**Email** - rrt48@cornell.edu  
**Phone** - (+1) 914-649-2007  

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: rrt48@cornell.edu # Allow visitors to contact you
