title: Richard (Ricky) Tegtmeier  # You can add your name here

logo: CV/1557353656217.jfif # Use a relative path to logo image 

description: PhD Candidate | Plant Breeding & Genetics 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: rrt48@cornell.edu # Allow visitors to contact you
